using System;
using System.Collections.Generic;
using System.Text;
using MySql.Data.MySqlClient;

namespace SQLFS.Database
{
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class DatabaseColumn : Attribute
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public MySqlDbType MySqlType { get; set; }

        public string IndexName { get; set; }
        public string IndexType { get; set; }
        public bool OverwriteIndex { get; set; }

        public bool IsSaved { get; set; } = true;
        public bool IsAutoGenerated { get; set; } = false;
        public bool IsKeyColumn { get; set; } = false;
        public bool IsCreated { get; set; } = true;

        public Func<object> ValueFunction { get; set; } = null;

        public DatabaseColumn(string name, string type, MySqlDbType mySqlType)
        {
            Name = name;
            Type = type;
            MySqlType = mySqlType;
        }

        public string GetIndexSql(string table) => IndexType != null
            ? $"CREATE INDEX {GetOverwriteSql()}{IndexName} ON {table} USING {IndexType}({Name})"
            : $"CREATE INDEX {GetOverwriteSql()}{IndexName} ON {table}({Name})";
        
        private string GetOverwriteSql() => OverwriteIndex ? "" : "IF NOT EXISTS ";
    }
}
